apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sync-waves
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: sync-waves
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
# teste rollout
# teste rollback id 02 argocd app history app
# id 03
# id 04
# id 05
# id 06
# id 07
# id 08
# id 09